name: Go CI Workflow
on: [push]
jobs:

  ci:
    name: Run CI on Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.14, 1.15, 1.16]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Lint & Test
      run: make setup-ci ci
